In [1]:
from model.MF.MF import MatrixFactorization

from model.MF.preprocessing import mean_ratings
from model.MF.preprocessing import normalized_ratings
from model.MF.preprocessing import ids_encoder
from model.MF.preprocessing import train_test_split
from model.MF.preprocessing import rating_matrix
from model.MF.preprocessing import get_examples
from model.MF.preprocessing import scale_ratings

import pandas as pd
import movielens
import splitter

In [3]:
df = movielens.load_pandas_df("1M")


/home/vinmike/Documents/GitHub/LLM4Rec-Dataloader/movielens.py:156: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv(


In [4]:
df

userID itemID  rating  timestamp
0             1    661     3.0  978302109
1             1    914     3.0  978301968
2             1   3408     4.0  978300275
3             1   2355     5.0  978824291
4             1   1197     3.0  978302268
...         ...    ...     ...        ...
1000203    6040   1091     1.0  956716541
1000204    6040   1094     5.0  956704887
1000205    6040    562     5.0  956704746
1000206    6040   1096     4.0  956715648
1000207    6040   1097     4.0  956715569

[1000208 rows x 4 columns]

In [5]:
ratings = pd.DataFrame(df[["userID", "itemID", "rating"]])

In [6]:
ratings.head()

userID itemID  rating
0       1    661     3.0
1       1    914     3.0
2       1   3408     4.0
3       1   2355     5.0
4       1   1197     3.0

In [7]:
# importing module
import sys

# printing all directories for 
# interpreter to search
sys.path

['/usr/lib/python310.zip',
 '/usr/lib/python3.10',
 '/usr/lib/python3.10/lib-dynload',
 '',
 '/home/vinmike/.local/lib/python3.10/site-packages',
 '/usr/local/lib/python3.10/dist-packages',
 '/usr/lib/python3/dist-packages']

In [48]:

ratings, uencoder, iencoder = ids_encoder(ratings)

m = ratings["userID"].nunique()   # total number of users
n = ratings["userID"].nunique()   # total number of items


In [9]:

raw_examples, raw_labels = get_examples(ratings)

In [10]:
print(raw_labels)

[3. 3. 4. ... 5. 4. 4.]


In [51]:
split_df = splitter.interactive_split(ratings)

[0.8, 0.2]


In [52]:
split_df[1]

userID  itemID  rating
0            0    3642     4.0
1            0    3234     5.0
2            0    1853     4.0
3            0     245     4.0
4            0    3432     3.0
...        ...     ...     ...
200010    6039    1796     3.0
200011    6039     203     4.0
200012    6039     265     4.0
200013    6039    1016     5.0
200014    6039     952     3.0

[200015 rows x 3 columns]

In [53]:
x_train = split_df[0][["userID", "itemID"]].to_numpy()
y_train = split_df[0][["rating"]].to_numpy().reshape(-1)

x_test = split_df[1][["userID", "itemID"]].to_numpy()
y_test = split_df[1][["rating"]].to_numpy().reshape(-1)

In [57]:
y_test

array([4., 5., 4., ..., 4., 5., 3.])

In [56]:
x_test

array([[   0, 3642],
       [   0, 3234],
       [   0, 1853],
       ...,
       [6039,  265],
       [6039, 1016],
       [6039,  952]])

In [58]:


MF = MatrixFactorization(m, n, k=10, alpha=0.01, lamb=1.5)

history = MF.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))



Training Matrix Factorization Model ...
k=10 	 alpha=0.01 	 lambda=1.5
epoch 1/10 - loss : 1.926 - val_loss : 1.934
epoch 2/10 - loss : 1.533 - val_loss : 1.537
epoch 3/10 - loss : 1.503 - val_loss : 1.506
epoch 4/10 - loss : 1.494 - val_loss : 1.497
epoch 5/10 - loss : 1.491 - val_loss : 1.493
epoch 6/10 - loss : 1.489 - val_loss : 1.491
epoch 7/10 - loss : 1.488 - val_loss : 1.49
epoch 8/10 - loss : 1.487 - val_loss : 1.49
epoch 9/10 - loss : 1.487 - val_loss : 1.489
epoch 10/10 - loss : 1.487 - val_loss : 1.489


In [59]:
MF.evaluate(x_test, y_test)

validation error : 1.489


1.4891639952848525